-- MySQL Script generated by MySQL Workbench
-- mar 26 sep 2023 19:38:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema labsol
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `labsol` ;

-- -----------------------------------------------------
-- Schema labsol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labsol` ;
USE `labsol` ;

-- -----------------------------------------------------
-- Table `labsol`.`solicitante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`solicitante` ;

CREATE TABLE IF NOT EXISTS `labsol`.`solicitante` (
  `idsolicitante` INT NOT NULL,
  `so_nombre` VARCHAR(35) NOT NULL,
  `so_apP` VARCHAR(35) NOT NULL,
  `so_apM` VARCHAR(35) NULL,
  `so_correo` VARCHAR(85) NOT NULL,
  `so_conthash` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idsolicitante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`institucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`institucion` ;

CREATE TABLE IF NOT EXISTS `labsol`.`institucion` (
  `idinstitucion` INT NOT NULL,
  `nombre oficial` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`idinstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`proyecto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`proyecto` ;

CREATE TABLE IF NOT EXISTS `labsol`.`proyecto` (
  `idproyecto` INT NOT NULL,
  `nombrePr` VARCHAR(85) NOT NULL,
  `solicitante_idsolicitante` INT NULL,
  `img` LONGTEXT NULL,
  PRIMARY KEY (`idproyecto`),
  INDEX `fk_proyecto_solicitante1_idx` (`solicitante_idsolicitante` ASC) ,
  CONSTRAINT `fk_proyecto_solicitante1`
    FOREIGN KEY (`solicitante_idsolicitante`)
    REFERENCES `labsol`.`solicitante` (`idsolicitante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`alumno` ;

CREATE TABLE IF NOT EXISTS `labsol`.`alumno` (
  `idalumno` INT NOT NULL,
  `al_nombre` VARCHAR(35) NOT NULL,
  `al_apP` VARCHAR(35) NOT NULL,
  `al_apM` VARCHAR(35) NULL,
  `al_correo` VARCHAR(35) NOT NULL,
  `al_conthash` VARCHAR(45) NOT NULL,
  `institucion_idinstitucion` INT NOT NULL,
  `proyecto_idproyecto` INT NULL,
  PRIMARY KEY (`idalumno`),
  INDEX `fk_alumno_institucion1_idx` (`institucion_idinstitucion` ASC) ,
  INDEX `fk_alumno_proyecto1_idx` (`proyecto_idproyecto` ASC) ,
  CONSTRAINT `fk_alumno_institucion1`
    FOREIGN KEY (`institucion_idinstitucion`)
    REFERENCES `labsol`.`institucion` (`idinstitucion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_alumno_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `labsol`.`proyecto` (`idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`ins_reducciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`ins_reducciones` ;

CREATE TABLE IF NOT EXISTS `labsol`.`ins_reducciones` (
  `reduccion` VARCHAR(25) NOT NULL,
  `institucion_idinstitucion` INT NOT NULL,
  PRIMARY KEY (`reduccion`, `institucion_idinstitucion`),
  INDEX `fk_ins_reducciones_institucion_idx` (`institucion_idinstitucion` ASC) ,
  CONSTRAINT `fk_ins_reducciones_institucion`
    FOREIGN KEY (`institucion_idinstitucion`)
    REFERENCES `labsol`.`institucion` (`idinstitucion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`siprints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`siprints` ;

CREATE TABLE IF NOT EXISTS `labsol`.`siprints` (
  `idsiprints` INT NOT NULL,
  `inicio` DATE NULL,
  `final` DATE NULL,
  `siprintscol` VARCHAR(45) NULL,
  `activo` TINYINT NOT NULL,
  `proyecto_idproyecto` INT NOT NULL,
  PRIMARY KEY (`idsiprints`, `proyecto_idproyecto`),
  INDEX `fk_siprints_proyecto1_idx` (`proyecto_idproyecto` ASC) ,
  CONSTRAINT `fk_siprints_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `labsol`.`proyecto` (`idproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`estadoAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`estadoAdmin` ;

CREATE TABLE IF NOT EXISTS `labsol`.`estadoAdmin` (
  `id` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `proyecto_idproyecto` INT NOT NULL,
  PRIMARY KEY (`id`, `proyecto_idproyecto`),
  INDEX `fk_estadoAdmin_proyecto1_idx` (`proyecto_idproyecto` ASC) ,
  CONSTRAINT `fk_estadoAdmin_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `labsol`.`proyecto` (`idproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`estadoAl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`estadoAl` ;

CREATE TABLE IF NOT EXISTS `labsol`.`estadoAl` (
  `id` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `proyecto_idproyecto` INT NOT NULL,
  PRIMARY KEY (`id`, `proyecto_idproyecto`),
  INDEX `fk_estadoAl_proyecto1_idx` (`proyecto_idproyecto` ASC) ,
  CONSTRAINT `fk_estadoAl_proyecto1`
    FOREIGN KEY (`proyecto_idproyecto`)
    REFERENCES `labsol`.`proyecto` (`idproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`tareas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`tareas` ;

CREATE TABLE IF NOT EXISTS `labsol`.`tareas` (
  `idtareas` INT NOT NULL,
  `tarea` LONGTEXT NOT NULL,
  `estadoAdmin_id` INT NULL,
  `estadoAl_id` INT NULL,
  `alumno_idalumno` INT NULL,
  `siprints_idsiprints` INT NOT NULL,
  `siprints_proyecto` INT NOT NULL,
  `tareas_idtareas` INT NOT NULL,
  PRIMARY KEY (`idtareas`),
  INDEX `fk_tareas_estadoAl1_idx` (`estadoAl_id` ASC) ,
  INDEX `fk_tareas_alumno1_idx` (`alumno_idalumno` ASC) ,
  INDEX `fk_tareas_siprints1_idx` (`siprints_idsiprints` ASC, `siprints_proyecto` ASC) ,
  INDEX `fk_tareas_tareas1_idx` (`tareas_idtareas` ASC) ,
  CONSTRAINT `fk_tareas_estadoAdmin1`
    FOREIGN KEY (`siprints_idsiprints` , `siprints_proyecto`)
    REFERENCES `labsol`.`estadoAdmin` (`id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tareas_estadoAl1`
    FOREIGN KEY (`estadoAl_id`)
    REFERENCES `labsol`.`estadoAl` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `labsol`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_siprints1`
    FOREIGN KEY (`siprints_idsiprints` , `siprints_proyecto`)
    REFERENCES `labsol`.`siprints` (`idsiprints` , `proyecto_idproyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tareas_tareas1`
    FOREIGN KEY (`tareas_idtareas`)
    REFERENCES `labsol`.`tareas` (`idtareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`tareas_has_alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`tareas_has_alumno` ;

CREATE TABLE IF NOT EXISTS `labsol`.`tareas_has_alumno` (
  `tareas_idtareas` INT NOT NULL,
  `tareas_siprints_idsiprints` INT NOT NULL,
  `tareas_siprints_proyecto_idproyecto` INT NOT NULL,
  `alumno_idalumno` INT NULL,
  PRIMARY KEY (`tareas_idtareas`, `tareas_siprints_idsiprints`, `tareas_siprints_proyecto_idproyecto`, `alumno_idalumno`),
  INDEX `fk_tareas_has_alumno_alumno1_idx` (`alumno_idalumno` ASC) ,
  CONSTRAINT `fk_tareas_has_alumno_tareas1`
    FOREIGN KEY (`tareas_idtareas` , `alumno_idalumno`)
    REFERENCES `labsol`.`tareas` (`idtareas` , `idtareas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tareas_has_alumno_alumno1`
    FOREIGN KEY (`alumno_idalumno`)
    REFERENCES `labsol`.`alumno` (`idalumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`comentario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`comentario` ;

CREATE TABLE IF NOT EXISTS `labsol`.`comentario` (
  `idcomentario` INT NOT NULL,
  `comentario` LONGTEXT NOT NULL,
  `alumno_idalumno` INT NOT NULL,
  `tareas_idtareas` INT NOT NULL,
  `tareas_siprints_idsiprints` INT NOT NULL,
  `tareas_siprints_proyecto_idproyecto` INT NOT NULL,
  PRIMARY KEY (`idcomentario`, `alumno_idalumno`, `tareas_idtareas`, `tareas_siprints_idsiprints`, `tareas_siprints_proyecto_idproyecto`),
  INDEX `fk_comentario_alumno1_idx` (`alumno_idalumno` ASC, `tareas_idtareas` ASC, `tareas_siprints_idsiprints` ASC, `tareas_siprints_proyecto_idproyecto` ASC) ,
  INDEX `fk_comentario_tareas1_idx` (`tareas_idtareas` ASC, `tareas_siprints_idsiprints` ASC, `tareas_siprints_proyecto_idproyecto` ASC) ,
  CONSTRAINT `fk_comentario_alumno1`
    FOREIGN KEY (`alumno_idalumno` , `tareas_idtareas` , `tareas_siprints_idsiprints` , `tareas_siprints_proyecto_idproyecto`)
    REFERENCES `labsol`.`alumno` (`idalumno` , `idalumno` , `idalumno` , `idalumno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentario_tareas1`
    FOREIGN KEY (`tareas_idtareas`)
    REFERENCES `labsol`.`tareas` (`idtareas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`etiquetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`etiquetas` ;

CREATE TABLE IF NOT EXISTS `labsol`.`etiquetas` (
  `idetiquetas` INT NOT NULL,
  `etiqueta` VARCHAR(60) NOT NULL,
  `tareas_idtareas` INT NOT NULL,
  `tareas_siprints_idsiprints` INT NOT NULL,
  `tareas_siprints_proyecto_idproyecto` INT NOT NULL,
  PRIMARY KEY (`idetiquetas`, `tareas_idtareas`, `tareas_siprints_idsiprints`, `tareas_siprints_proyecto_idproyecto`),
  INDEX `fk_etiquetas_tareas1_idx` (`tareas_idtareas` ASC, `tareas_siprints_idsiprints` ASC, `tareas_siprints_proyecto_idproyecto` ASC) ,
  CONSTRAINT `fk_etiquetas_tareas1`
    FOREIGN KEY (`tareas_idtareas`)
    REFERENCES `labsol`.`tareas` (`idtareas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labsol`.`administradores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labsol`.`administradores` ;

CREATE TABLE IF NOT EXISTS `labsol`.`administradores` (
  `idadministradores` INT NOT NULL,
  `ad_nombre` VARCHAR(45) NOT NULL,
  `ad_apellidoP` VARCHAR(45) NOT NULL,
  `ad_apellidoM` VARCHAR(45) NULL,
  `ad_correo` VARCHAR(45) NOT NULL,
  `ad_contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadministradores`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
